language: python
python:
  - "2.7"
services:
  - rabbitmq
  - postgresql
before_install:
  - git clone git://github.com/openspending/openspending-installer.git
before_script:
  - true
install:
  - sudo openspending-installer/vagrant/install.sh
script: "nosetests"
